### ISSUE TITLE
Human evaluation data

### ISSUE THREAD

**Issue by vishaal27** [Shentao-YANG/Dense_Reward_T2I#1]
Hey, thanks for your great work and releasing it publicly.
I am quite interested in the human evaluation data that you collected (Table 3, Appendix D.3). Are you planning to release the exact prompts used, the images used in each binary comparison, and the human preferences for each sample pair? This would be very helpful!

**Comment by Shentao-YANG** [comment]
Hi, thanks for the good idea!
We will communicate with relevant parties and work on the logistic/technical/procedural issues pertaining to releasing those data. 
Meanwhile, to better communicate with relevant parties, may we kindly ask if you have any specific usage of those data in mind?

**Comment by vishaal27** [comment]
Yes I am just generally interested in getting access to the human preference data for helping with training diffusion models to be more aligned with user intentions.

**Comment by Shentao-YANG** [comment]
Thanks for the clarification. We will factor this in our communication with relevant parties. 
In this meantime, you may also consider open-sourced scorers pre-trained from large-scale human preference data, such as [ImageReward](https://github.com/THUDM/ImageReward) and [HPSv2](https://github.com/tgxs002/HPSv2) used in our paper. 
I will close this issue and will provide updates if available.
Thanks for your interest in our work and stay tuned!
